config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:new, :show, :index] do
    resources :reviews, only: [:new]
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian), message: "%{value} is not a valid size"}

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant
  end

  def new
    @restaurant = Restaurant.new
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def top
  #   @restaurants = Restaurant.where(rating: 5)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <li><%=  link_to restaurant.name, restaurant_path(restaurant) %> </li>
<% end %>

<%= link_to "Generate new Restaurant", new_restaurant_path, class: "btn btn-primary"  %>

app/views/restaurants/new.html.erb
<h1>New</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name, label: 'Your restaurant name please', error: 'restaurant is mandatory, please specify one' %>
  <%= f.input :address, label: 'Address.' %>
  <%= f.input :category, label: 'Category' %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Single Restaurant</h1>

<p> Name: <%=  @restaurant.name  %> </p>
<p> Address: <%=  @restaurant.address  %> </p>
<p> Cetgory: <%=  @restaurant.category  %> </p>
<p> <%=  link_to "Back", restaurants_path %> </p>